/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-02-25 10:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/templates/header.jsp", Long.valueOf(1519551155770L));
    _jspx_dependants.put("/WEB-INF/views/templates/footer.jsp", Long.valueOf(1519203067898L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1518785686794L));
    _jspx_dependants.put("jar:file:/E:/DtProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/dtpro/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/E:/DtProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/dtpro/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1482320444000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar", Long.valueOf(1519291764013L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">WebSiteName</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("      ");
      if (_jspx_meth_security_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       <li><a href=\"/dtpro/listProducts\">Products</a></li>\r\n");
      out.write("       ");
      if (_jspx_meth_security_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("     <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\tul > li\r\n");
      out.write("\t{\r\n");
      out.write("\tmargin-right:25px;\r\n");
      out.write("\tfont-weight:lighter;\r\n");
      out.write("\tcursor:pointer\r\n");
      out.write("\t}\r\n");
      out.write("li.active\r\n");
      out.write("{\r\n");
      out.write("border-bottom:3px solid silver;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item-photo\r\n");
      out.write("{\"src/main/webapp/WEB-INF/views/showProduct.jsp\"\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("border-right:1px solid #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write(".menu-items\r\n");
      out.write("{\r\n");
      out.write("list-style-type:none;\r\n");
      out.write("font-size:11px;\r\n");
      out.write("display:inline-flex;\r\n");
      out.write("margin-bottom:0;\r\n");
      out.write("margin-top:20px\r\n");
      out.write("}\r\n");
      out.write(".btn-success\r\n");
      out.write("{\r\n");
      out.write("width:100%;\r\n");
      out.write("border-radius:0;\r\n");
      out.write("}\r\n");
      out.write(".section\r\n");
      out.write("{\r\n");
      out.write("width:100%;\r\n");
      out.write("margin-left:-15px;\r\n");
      out.write("padding:2px;\r\n");
      out.write("padding-left:15px;\r\n");
      out.write("padding-right:15px;background:#f8f9f9}\r\n");
      out.write(".title-price{margin-top:30px;margin-bottom:0;color:black}\r\n");
      out.write(".title-attr{margin-top:0;margin-bottom:0;color:black;}\r\n");
      out.write(".btn-minus{cursor:pointer;font-size:7px;display:flex;align-items:center;padding:5px;padding-left:10px;padding-right:10px;border:1px solid gray;border-radius:2px;border-right:0;}\r\n");
      out.write(".btn-plus{cursor:pointer;font-size:7px;display:flex;align-items:center;padding:5px;padding-left:10px;padding-right:10px;border:1px solid gray;border-radius:2px;border-left:0;}\r\n");
      out.write("div.section > div {width:100%;display:inline-flex;}\r\n");
      out.write("div.section > div > input {margin:0;padding-left:5px;font-size:10px;padding-right:5px;max-width:18%;text-align:center;}\r\n");
      out.write(".attr,.attr2{cursor:pointer;margin-right:5px;height:20px;font-size:10px;padding:2px;border:1px solid gray;border-radius:2px;}\r\n");
      out.write(".attr.active,.attr2.active{ border:1px solid orange;}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 426px) {\r\n");
      out.write("    .container {margin-top:0px !important;}\r\n");
      out.write("    .container > .row{padding:0 !important;}\r\n");
      out.write("    .container > .row > .col-xs-12.col-sm-5{\r\n");
      out.write("        padding-right:0 ;    \r\n");
      out.write("    }\r\n");
      out.write("    .container > .row > .col-xs-12.col-sm-9 > div > p{\r\n");
      out.write("        padding-left:0 !important;\r\n");
      out.write("        padding-right:0 !important;\r\n");
      out.write("    }\r\n");
      out.write("    .container > .row > .col-xs-12.col-sm-9 > div > ul{\r\n");
      out.write("        padding-left:10px !important;\r\n");
      out.write("        \r\n");
      out.write("    }            \r\n");
      out.write("    .section{width:104%;}\r\n");
      out.write("    .menu-items{padding-left:0;}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("               <div class=\"col-xs-4 item-photo\">\r\n");
      out.write("                    <img style=\"max-width:100%;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resources/images/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xs-5\" style=\"border:0px solid gray\">\r\n");
      out.write("                    <!-- Datos del vendedor y titulo del producto -->\r\n");
      out.write("                    <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>    \r\n");
      out.write("                    <h5 style=\"color:#337ab7\">Quantity Available <small style=\"color:#337ab7\">(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pQuantity }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</small></h5>\r\n");
      out.write("        \r\n");
      out.write("                    <!-- Precios -->\r\n");
      out.write("                    <h6 class=\"title-price\"><small>Price</small></h6>\r\n");
      out.write("                    <h3 style=\"margin-top:0px;\">&#8377; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("        \r\n");
      out.write("                    <!-- Detalles especificos del producto -->\r\n");
      out.write("                    <div class=\"section\">\r\n");
      out.write("                        <h6 class=\"title-attr\" style=\"margin-top:15px;\" ><small>COLOR</small></h6>                    \r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"attr\" style=\"width:25px;background:#5a5a5a;\"></div>\r\n");
      out.write("                            <div class=\"attr\" style=\"width:25px;background:white;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- <div class=\"section\" style=\"padding-bottom:5px;\">\r\n");
      out.write("                        <h6 class=\"title-attr\"><small>CAPACIDAD</small></h6>                    \r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"attr2\">16 GB</div>\r\n");
      out.write("                            <div class=\"attr2\">32 GB</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> --> \r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addIntoCart\" method=\"post\">  \r\n");
      out.write("                    <div class=\"section\" style=\"padding-bottom:20px;\">\r\n");
      out.write("                        <h6 class=\"title-attr\"><small>Quantity</small></h6> \r\n");
      out.write("                        <input type=\"hidden\" name=\"pid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>                   \r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"btn-minus\"><span class=\"glyphicon glyphicon-minus\"></span></div>\r\n");
      out.write("                            <input type=\"text\" name=\"quantity\" value=\"1\"/>\r\n");
      out.write("                            <div class=\"btn-plus\"><span class=\"glyphicon glyphicon-plus\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>                \r\n");
      out.write("\r\n");
      out.write("                    <!-- Botones de compra -->\r\n");
      out.write("                    <div class=\"section\" style=\"padding-bottom:20px;\">\r\n");
      out.write("                    \r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-success\"> <span style=\"margin-right:20px\" class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span> Add to Cart</button>\r\n");
      out.write("                        <h6><a href=\"#\"><span class=\"glyphicon glyphicon-heart-empty\" style=\"cursor:pointer;\"></span> Agregar a lista de deseos</a></h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>                              \r\n");
      out.write("        \r\n");
      out.write("                <div class=\"col-xs-9\">\r\n");
      out.write("                    <ul class=\"menu-items\">\r\n");
      out.write("                        <li class=\"active\">Detalle del producto</li>\r\n");
      out.write("                        <li>GarantÃ­a</li>\r\n");
      out.write("                        <li>Vendedor</li>\r\n");
      out.write("                        <li>EnvÃ­o</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div style=\"width:100%;border-top:1px solid silver\">\r\n");
      out.write("                        <p style=\"padding:15px;\">\r\n");
      out.write("                            <small>\r\n");
      out.write("                            Stay connected either on the phone or the Web with the Galaxy S4 I337 from Samsung. With 16 GB of memory and a 4G connection, this phone stores precious photos and video and lets you upload them to a cloud or social network at blinding-fast speed. With a 17-hour operating life from one charge, this phone allows you keep in touch even on the go. \r\n");
      out.write("        \r\n");
      out.write("                            With its built-in photo editor, the Galaxy S4 allows you to edit photos with the touch of a finger, eliminating extraneous background items. Usable with most carriers, this smartphone is the perfect companion for work or entertainment.\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <small>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>Super AMOLED capacitive touchscreen display with 16M colors</li>\r\n");
      out.write("                                <li>Available on GSM, AT T, T-Mobile and other carriers</li>\r\n");
      out.write("                                <li>Compatible with GSM 850 / 900 / 1800; HSDPA 850 / 1900 / 2100 LTE; 700 MHz Class 17 / 1700 / 2100 networks</li>\r\n");
      out.write("                                <li>MicroUSB and USB connectivity</li>\r\n");
      out.write("                                <li>Interfaces with Wi-Fi 802.11 a/b/g/n/ac, dual band and Bluetooth</li>\r\n");
      out.write("                                <li>Wi-Fi hotspot to keep other devices online when a connection is not available</li>\r\n");
      out.write("                                <li>SMS, MMS, email, Push Mail, IM and RSS messaging</li>\r\n");
      out.write("                                <li>Front-facing camera features autofocus, an LED flash, dual video call capability and a sharp 4128 x 3096 pixel picture</li>\r\n");
      out.write("                                <li>Features 16 GB memory and 2 GB RAM</li>\r\n");
      out.write("                                <li>Upgradeable Jelly Bean v4.2.2 to Jelly Bean v4.3 Android OS</li>\r\n");
      out.write("                                <li>17 hours of talk time, 350 hours standby time on one charge</li>\r\n");
      out.write("                                <li>Available in white or black</li>\r\n");
      out.write("                                <li>Model I337</li>\r\n");
      out.write("                                <li>Package includes phone, charger, battery and user manual</li>\r\n");
      out.write("                                <li>Phone is 5.38 inches high x 2.75 inches wide x 0.13 inches deep and weighs a mere 4.59 oz </li>\r\n");
      out.write("                            </ul>  \r\n");
      out.write("                        </small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            //-- Click on detail\r\n");
      out.write("            $(\"ul.menu-items > li\").on(\"click\",function(){\r\n");
      out.write("                $(\"ul.menu-items > li\").removeClass(\"active\");\r\n");
      out.write("                $(this).addClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            $(\".attr,.attr2\").on(\"click\",function(){\r\n");
      out.write("                var clase = $(this).attr(\"class\");\r\n");
      out.write("\r\n");
      out.write("                $(\".\" + clase).removeClass(\"active\");\r\n");
      out.write("                $(this).addClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            //-- Click on QUANTITY\r\n");
      out.write("            $(\".btn-minus\").on(\"click\",function(){\r\n");
      out.write("                var now = $(\".section > div > input\").val();\r\n");
      out.write("                if ($.isNumeric(now)){\r\n");
      out.write("                    if (parseInt(now) -1 > 0){ now--;}\r\n");
      out.write("                    $(\".section > div > input\").val(now);\r\n");
      out.write("                }else{\r\n");
      out.write("                    $(\".section > div > input\").val(1);\r\n");
      out.write("                }\r\n");
      out.write("            })            \r\n");
      out.write("            $(\".btn-plus\").on(\"click\",function(){\r\n");
      out.write("                var now = $(\".section > div > input\").val();\r\n");
      out.write("                if ($.isNumeric(now)){\r\n");
      out.write("                    $(\".section > div > input\").val(parseInt(now)+1);\r\n");
      out.write("                }else{\r\n");
      out.write("                    $(\".section > div > input\").val(\"1\");\r\n");
      out.write("                }\r\n");
      out.write("            })                        \r\n");
      out.write("        }) \r\n");
      out.write("        </script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <h3 class=\"footertext\">About Us:</h3>\r\n");
      out.write("            <br>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <center>\r\n");
      out.write("                  <img src=\"http://oi60.tinypic.com/w8lycl.jpg\" class=\"img-circle\" alt=\"the-brains\">\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <h4 class=\"footertext\">Programmer</h4>\r\n");
      out.write("                  <p class=\"footertext\">You can thank all the crazy programming here to this guy.<br>\r\n");
      out.write("                </center>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <center>\r\n");
      out.write("                  <img src=\"http://oi60.tinypic.com/2z7enpc.jpg\" class=\"img-circle\" alt=\"...\">\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <h4 class=\"footertext\">Artist</h4>\r\n");
      out.write("                  <p class=\"footertext\">All the images here are hand drawn by this man.<br>\r\n");
      out.write("                </center>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <center>\r\n");
      out.write("                  <img src=\"http://oi61.tinypic.com/307n6ux.jpg\" class=\"img-circle\" alt=\"...\">\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <h4 class=\"footertext\">Designer</h4>\r\n");
      out.write("                  <p class=\"footertext\">This pretty site and the copy it holds are all thanks to this guy.<br>\r\n");
      out.write("                </center>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            <p><center><a href=\"#\">Contact Stuff Here</a> <p class=\"footertext\">Copyright 2014</p></center></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_security_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_security_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_security_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/templates/header.jsp(22,6) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthorize_005f0.setAccess("hasRole('ROLE_ADMIN')");
      int _jspx_eval_security_005fauthorize_005f0 = _jspx_th_security_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_security_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("       <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/admin/adding\">Admin</a></li>\r\n");
        out.write("       ");
      }
      if (_jspx_th_security_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
      _jspx_th_security_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_security_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_security_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/templates/header.jsp(26,7) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthorize_005f1.setAccess("hasRole('ROLE_ADMIN')");
      int _jspx_eval_security_005fauthorize_005f1 = _jspx_th_security_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_security_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("      <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Page 1 <span class=\"caret\"></span></a>\r\n");
        out.write("         \r\n");
        out.write("        <ul class=\"dropdown-menu\">\r\n");
        out.write("          <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/admin/showProducts\">Products</a></li>\r\n");
        out.write("          <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/admin/showCategory\">Category</a></li>\r\n");
        out.write("          <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/admin/showSuppliers\">Supplier</a></li>\r\n");
        out.write("        </ul>\r\n");
        out.write("      </li>\r\n");
        out.write("      ");
      }
      if (_jspx_th_security_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f1);
      _jspx_th_security_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_security_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/templates/header.jsp(38,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <li><a href=\"registerUser\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
          out.write("      <li><a href=\"login\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/templates/header.jsp(43,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <li><a href=\"/dtpro/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/userProfile\"><span class=\"glyphicon glyphicon-user\"></span> Welcome ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </a></li>\r\n");
          out.write("      <li><a href=\"/dtpro/cart\">cart</a></li>\r\n");
          out.write("      <li><a href=\"");
          if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\"><span class=\"glyphicon glyphicon-log-in\"></span> Logout</a></li>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/templates/header.jsp(46,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/j_spring_security_logout");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
